services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: Bank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    image: technicaltest-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/Bank
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"

volumes:
  db-data:


# services:
#   db:
#     image: postgres:15
#     restart: unless-stopped
#     environment:
#       POSTGRES_DB: Bank
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: admin
#     ports:
#       - "5432:5432"
#     volumes:
#       - db-data:/var/lib/postgresql/data

#   app:
#     build: .
#     depends_on:
#       - db
#     environment:
#       SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/Bank
#       SPRING_DATASOURCE_USERNAME: postgres
#       SPRING_DATASOURCE_PASSWORD: admin
#       SPRING_JPA_HIBERNATE_DDL_AUTO: update
#     ports:
#       - "8080:8080"
#     restart: on-failure

# volumes:
#   db-data:
